Update minimum golang version to v1.21.7
ava-labs/subnet-evm pull request #1088
Opened 2024-02-07 21:06 UTC by dhrubabasu

2024-02-07 21:12 UTC, darioush submitted a review, later dismissed

2024-02-08 11:22 UTC, ceyonur approved these changes

2024-02-08 11:24 UTC, ceyonur requested changes
sorry for earlier approval.

2024-02-08 11:24 UTC, ceyonur commented on go.mod
> +	github.com/ava-labs/avalanchego v1.11.0-rc.1.0.20240207163634-e248179ae759
can we also update avalanchego version in `versions.sh`?

2024-02-08 14:55 UTC, ceyonur approved these changes

2024-02-09 18:49 UTC, ceyonur approved these changes

2024-02-09 19:35 UTC, darioush approved these changes

2024-02-09 19:35 UTC, merged