`ci`: Skip monitoring if secrets are not present
ava-labs/subnet-evm pull request #1137
Opened 2024-03-28 17:45 UTC by marun

Metrics and logs can only be collected if the required secrets are present, but they will not be available to jobs executing against PRs for forks.

2024-03-28 17:45 UTC, ceyonur approved these changes

2024-03-28 18:35 UTC, darioush approved these changes

2024-03-28 19:22 UTC, ceyonur commented on .github/workflows/tests.yml
> +        if: secrets.PROMETHEUS_ID != ''
hmm this file is not working https://github.com/ava-labs/subnet-evm/actions/runs/8471478509/workflow
I think it should be ${{ secrets.PROMETHEUS_ID }}

2024-03-28 21:17 UTC, ceyonur requested changes
requesting changes in case auto-merge triggers somehow before fixing this

2024-04-08 16:44 UTC, ceyonur approved these changes

2024-04-08 16:48 UTC, darioush approved these changes

2024-04-08 19:20 UTC, merged