remove airdrop from genesis file
ava-labs/subnet-evm pull request #115
Opened 2022-05-27 15:12 UTC by yulin-dong

2022-05-27 16:09 UTC, patrick-ogrady commented on networks/11111/genesis.json
> -  "airdropHash": "0xccbf8e430b30d08b5b3342208781c40b373d1b5885c1903828f367230a2568da",
This will break WAGMI

2022-05-31 13:53 UTC, hexfusion approved these changes

2022-05-31 13:57 UTC, hexfusion requested changes
can we explain why this change is needed please

2022-05-31 16:42 UTC, aaronbuchwald commented on README.md
> +## Create an EVM Subnet on Local
```suggestion
## Create an EVM Subnet on a Local Network
```

2022-05-31 16:42 UTC, aaronbuchwald approved these changes

2022-05-31 20:01 UTC, merged