update WAGMI RPC URL
ava-labs/subnet-evm pull request #73
Opened 2022-04-04 00:35 UTC by Julian-dev28

Updated RPC URL to the most current endpoint

2022-04-04 04:15 UTC, patrick-ogrady commented on README.md
> -![metamask](./imgs/metamask.png)
The block explorer in this image should be: https://subnets.avax.network/wagmi/wagmi-chain-testnet/explorer

2022-04-04 14:20 UTC, patrick-ogrady requested changes
image is incorrect...should update explorer.

2022-04-04 14:59 UTC, Julian-dev28 commented
@patrick-ogrady 

Should be good to go now

2022-04-04 15:14 UTC, Julian-dev28 reviewed
@patrick-ogrady 

Good to go!

2022-04-05 08:05 UTC, ceyonur approved these changes
LGTM

2022-04-06 16:08 UTC, patrick-ogrady approved these changes

2022-04-06 16:09 UTC, merged